### ISSUE TITLE
There are some problems in some site.

### ISSUE THREAD

**Issue by bdim404** [bdim404/HackerNews-Summarize-Telegram-Bot#30]
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/telegram/ext/_application.py", line 1195, in process_update
    await coroutine
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/telegram/ext/_basehandler.py", line 153, in handle_update
    return await self.callback(update, context)
  File "/Volumes/bdim'stonge/work_and_learn/python learning/hackernewSummarizeBot.py", line 102, in handle_message
    content = h2t.handle(html)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/html2text/__init__.py", line 142, in handle
    self.feed(data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/html2text/__init__.py", line 139, in feed
    super().feed(data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/html/parser.py", line 110, in feed
    self.goahead(0)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/html/parser.py", line 170, in goahead
    k = self.parse_starttag(i)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/html/parser.py", line 344, in parse_starttag
    self.handle_starttag(tag, attrs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/html2text/__init__.py", line 191, in handle_starttag
    self.handle_tag(tag, dict(attrs), start=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/html2text/__init__.py", line 327, in handle_tag
    tag_style = element_style(attrs, self.style_def, parent_style)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/html2text/utils.py", line 72, in element_style
    assert attrs["class"] is not None
AssertionError
```

**Comment by bdim404** [comment]
fixed in https://github.com/bdim404/HackerNews-Summarize-Telegram-Bot/pull/31
